Angular course
glebgol/angular-eshop pull request #1
Opened 2024-07-24 12:17 UTC by glebgol

2024-07-27 19:40 UTC, ShkrobNastya requested changes

2024-07-27 19:40 UTC, ShkrobNastya commented on src/app/products/pages/products-page/products-page.component.ts
> +      this.filterBadges.set('minRating', 'Min Rating 0')
imagine, that you have 30 filters, you can't do condition for every
please, redo it in a loop

2024-07-27 19:40 UTC, ShkrobNastya commented on src/app/products/pages/products-page/products-page.component.ts
> +    return formData.maxRatingInvalid || formData.maxRating == null || p.rating.rate <= formData.maxRating;
please, use json server operation for filtering purpose as was mentioned in angular course

products must be filtered by BE (as on real projects)

2024-07-27 19:40 UTC, ShkrobNastya commented on src/app/products/pages/products-page/products-page.component.ts
> +    });
for what is it?

2024-07-27 19:40 UTC, ShkrobNastya commented on src/app/products/filters-form.ts
.model.ts

2024-07-27 19:40 UTC, ShkrobNastya commented on src/app/products/filters-form.ts
> +  maxRatingInvalid: boolean,
is it really required?

2024-07-27 19:40 UTC, ShkrobNastya commented on src/app/shared/components/header/header.component.html
> +    <a href="products">Shop</a>
href reload page, for spa we use routerLink

2024-07-27 19:40 UTC, ShkrobNastya commented on src/app/shared/models/product.ts
would be better to make all fields optional as you can't be sure what you will receive

2024-07-27 19:40 UTC, ShkrobNastya commented on src/app/auth/pages/auth-page/auth-page.component.html
for login we shouldn't have length validation
![image](https://github.com/user-attachments/assets/5e89253c-65d3-49c1-832c-fc2f1f2268f7)

2024-07-27 19:41 UTC, ShkrobNastya commented
also please change project structure
as example you can use it:
![image](https://github.com/user-attachments/assets/8025fce9-f87b-45d3-87d9-c9eb9a2e23fb)

2024-07-27 19:46 UTC, ShkrobNastya commented
also for future(you don't need to fix it): you can't be sure that all data will be receive, so for such block we use ngIf + ?.
![image](https://github.com/user-attachments/assets/c4b2711f-1540-46b1-b228-abf699b1b3c2)

`        <p *ngIf="product?.title">{{product.title}}</p>`

2024-07-30 09:33 UTC, glebgol commented on src/app/products/components/product/product.component.html
> +    <button class="button" (click)="$event.stopPropagation()" routerLink="../product/edit/{{product.id}}">Edit</button>
As it is written in the task "Each product tile should be clickable and lead to Product Details page". 
So, I added routerLink="../products/{{product.id}}" on parent div, and parent routerlink is active on all child elements. And I use here event.stopPropagation() on child elements to prevent clicking on parent's routerlink

2024-07-30 09:34 UTC, glebgol commented on src/app/products/pages/products-page/products-page.component.ts
> +    });
I used it for reloading page when back button clicked. I need it because filters form is being created based on request params at the stage of page creation, and when back button clicked page doesn't reload and form remains in the same state and found products don't match request params. 
Now I come up with better solution, I subscribe to the requst params and update the form values when they changed

2024-08-02 20:11 UTC, ShkrobNastya requested changes

2024-08-02 20:11 UTC, ShkrobNastya commented on src/app/products/components/filters-form/filters-form.component.html
> +      </mat-slider>
just for future - you don't to fix it
be careful with range filter, better to add some debounce, or send request after user releases the mouse button

2024-08-02 20:11 UTC, ShkrobNastya commented on src/app/shared/services/user.service.ts
please, recheck project structure that I shared with you, services can't be in shared module
each service for the corresponding module

2024-08-05 16:44 UTC, ShkrobNastya approved these changes

2024-08-05 16:59 UTC, merged

2024-08-05 17:42 UTC, ShkrobNastya reviewed
хотела ещё добавить пару моментов: 
-core module в скоупе данного проекта смысла не имеет, а так всегда присутствует:
это то, что подключается ко всему проекту, shared же к каким-то модулям подключается, к каким-то нет
-ещё заметила, что ты всю основную логику в компонентах пишешь, обычно в компонентах у нас реакции на действия пользователя: delete/submit/click, а что-то большее, какая-то обработка данных выносится в сервисы